title: "张志敏的技术专栏"
subtitle: "我是一个靠谱的程序员, 目前关注 MonoTouch、 Mono for Android、 Silverlight、  ASP.NET MVC 以及 NHibernate。"
public_url: "https://beginor.github.io"
keywords: "mono, ios, android, silverlight, asp.net mvc, asp.net web api, nhibernate, c, sql server, xml, linux, mac osx"
owner:
  name: "张志敏"
  mail: "beginor(at)qq.com"
  weibo: "https://weibo.com/beginor"
disqus:
  short_name: "beginor-github"
paginate: 12
exclude: ["start-jekyll.sh", "start-jekyll.bat", "bower.json"]
encoding: utf-8
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-coffeescript
  - jekyll-paginate
host: 127.0.0.1
port: 4004
